package com.frontierscan.article;

import com.frontierscan.auth.UserAccount;
import com.frontierscan.auth.UserAccountRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 文章筛选业务集成测试。
 * <p>
 * <b>测试策略：</b>使用 {@code @SpringBootTest} 加载完整 Spring 上下文，
 * H2 内存数据库（PostgreSQL 兼容模式）替代真实数据库。
 * 测试覆盖：信息看板关键词/标签/日期筛选、收藏页筛选。
 * </p>
 *
 * <p><b>数据清理：</b>每个 {@code @BeforeEach} 清空测试表，确保测试间无数据污染。</p>
 */
@SpringBootTest
@ActiveProfiles("test")
@DisplayName("文章筛选集成测试")
class ArticleFilterIntegrationTest {

    @Autowired
    private ArticleService articleService;

    @Autowired
    private ArticleRepository articleRepository;

    @Autowired
    private FavoriteRepository favoriteRepository;

    @Autowired
    private UserAccountRepository userRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private Long userId;
    private Article articleTitle;
    private Article articleSummary;
    private Article articleRecent;
    private Article articleOld;

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS article_tags");
        favoriteRepository.deleteAll();
        articleRepository.deleteAll();
        userRepository.deleteAll();

        // 手动创建 article_tags 表（Flyway 被禁用，供标签筛选测试用）
        jdbcTemplate.execute("""
                CREATE TABLE article_tags (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    article_id BIGINT NOT NULL,
                    tag_id BIGINT NOT NULL,
                    tag_domain VARCHAR(100),
                    score FLOAT
                )
                """);

        UserAccount user = new UserAccount();
        user.setUsername("filter-test-user");
        user.setPasswordHash("hash");
        user.setRole("USER");
        user.setStatus("ACTIVE");
        user.setCreatedAt(OffsetDateTime.now());
        user.setUpdatedAt(OffsetDateTime.now());
        userId = userRepository.save(user).getId();

        articleTitle = articleRepository.save(createArticle(
                "AI 深度学习在医疗领域的应用趋势", "医疗行业正在引入AI技术...", 0));
        articleSummary = articleRepository.save(createArticle(
                "2026年云计算趋势报告", "深度学习驱动的云原生架构...", 1));
        articleRecent = articleRepository.save(createArticle(
                "前端技术趋势 2026", "React、Vue 和 Svelte 的发展", 2));
        articleOld = articleRepository.save(createArticle(
                "数据库性能优化实践", "PostgreSQL 查询优化技巧", 30));

        jdbcTemplate.update("INSERT INTO article_tags (article_id, tag_id, tag_domain) VALUES (?, 1, '科技')",
                articleTitle.getId());
        jdbcTemplate.update("INSERT INTO article_tags (article_id, tag_id, tag_domain) VALUES (?, 2, '科技')",
                articleRecent.getId());

        articleService.toggleFavorite(userId, articleTitle.getId());
        articleService.toggleFavorite(userId, articleRecent.getId());
    }

    @Nested
    @DisplayName("信息看板筛选")
    class DashboardFiltering {

        @Test
        @DisplayName("无筛选条件返回全部文章")
        void shouldReturnAllWithoutFilters() {
            Page<Article> result = articleService.listByUser(userId, null, null,
                    null, null, null, null, PageRequest.of(0, 10));
            assertThat(result.getContent()).hasSize(4);
        }

        @Test
        @DisplayName("关键词按标题匹配")
        void shouldFilterByKeywordInTitle() {
            Page<Article> result = articleService.listByUser(userId, null, null,
                    "AI", null, null, null, PageRequest.of(0, 10));
            assertThat(result.getContent()).hasSize(1);
        }

        @Test
        @DisplayName("关键词按摘要匹配")
        void shouldFilterByKeywordInSummary() {
            Page<Article> result = articleService.listByUser(userId, null, null,
                    "深度学习", null, null, null, PageRequest.of(0, 10));
            assertThat(result.getContent()).hasSize(2);
        }

        @Test
        @DisplayName("标签筛选")
        void shouldFilterByTagId() {
            Page<Article> result = articleService.listByUser(userId, null, null,
                    null, 1L, null, null, PageRequest.of(0, 10));
            assertThat(result.getContent()).hasSize(1);
        }

        @Test
        @DisplayName("无匹配标签返回空")
        void shouldReturnEmptyForBadTag() {
            Page<Article> result = articleService.listByUser(userId, null, null,
                    null, 999L, null, null, PageRequest.of(0, 10));
            assertThat(result.getContent()).isEmpty();
        }

        @Test
        @DisplayName("起始日期筛选")
        void shouldFilterByStartDate() {
            String start = LocalDate.now().minusDays(1).toString();
            Page<Article> result = articleService.listByUser(userId, null, null,
                    null, null, start, null, PageRequest.of(0, 10));
            assertThat(result.getTotalElements()).isGreaterThanOrEqualTo(2);
        }

        @Test
        @DisplayName("截止日期筛选")
        void shouldFilterByEndDate() {
            String end = LocalDate.now().minusDays(29).toString();
            Page<Article> result = articleService.listByUser(userId, null, null,
                    null, null, null, end, PageRequest.of(0, 10));
            assertThat(result.getContent()).hasSize(1);
        }

        @Test
        @DisplayName("组合筛选")
        void shouldFilterCombined() {
            String start = LocalDate.now().minusDays(5).toString();
            Page<Article> result = articleService.listByUser(userId, null, null,
                    "前端", 2L, start, null, PageRequest.of(0, 10));
            assertThat(result.getContent()).hasSize(1);
        }

        @Test
        @DisplayName("分页与筛选共存")
        void shouldPaginateWithFilters() {
            Page<Article> p1 = articleService.listByUser(userId, null, null,
                    null, null, null, null, PageRequest.of(0, 2));
            assertThat(p1.getContent()).hasSize(2);
            assertThat(p1.getTotalElements()).isEqualTo(4);

            Page<Article> p2 = articleService.listByUser(userId, null, null,
                    null, null, null, null, PageRequest.of(1, 2));
            assertThat(p2.getContent()).hasSize(2);
        }
    }

    @Nested
    @DisplayName("收藏页筛选")
    class FavoritesFiltering {

        @Test
        @DisplayName("无筛选返回全部收藏")
        void shouldReturnAllFavorites() {
            assertThat(articleService.listFavoriteArticles(userId)).hasSize(2);
        }

        @Test
        @DisplayName("关键词筛选收藏（标题匹配）")
        void shouldFilterByKeyword() {
            var result = articleService.listFavoriteArticlesWithFilters(
                    userId, "AI", null, null, null);
            assertThat(result).hasSize(1);
            assertThat(result.get(0).title()).contains("AI");
        }

        @Test
        @DisplayName("标签筛选收藏")
        void shouldFilterByTagId() {
            var result = articleService.listFavoriteArticlesWithFilters(
                    userId, null, 2L, null, null);
            assertThat(result).hasSize(1);
        }

        @Test
        @DisplayName("组合筛选收藏")
        void shouldFilterCombined() {
            var result = articleService.listFavoriteArticlesWithFilters(
                    userId, "AI", 1L, null, null);
            assertThat(result).hasSize(1);
        }

        @Test
        @DisplayName("无匹配收藏返回空")
        void shouldReturnEmptyForNoMatch() {
            var result = articleService.listFavoriteArticlesWithFilters(
                    userId, "不存在的关键词", null, null, null);
            assertThat(result).isEmpty();
        }
    }

    private Article createArticle(String title, String summary, int daysAgo) {
        Article article = new Article();
        article.setUserId(userId);
        article.setSiteId(1L);
        article.setCategoryId(1L);
        article.setTitle(title);
        article.setSummary(summary);
        article.setSourceUrl("https://example.com/" + Math.abs(title.hashCode()));
        article.setSourceHash("hash-" + title);
        article.setContentExcerpt(summary);
        article.setPublishedAt(OffsetDateTime.now().minusDays(daysAgo));
        article.setCollectedAt(OffsetDateTime.now());
        article.setCreatedAt(OffsetDateTime.now());
        return article;
    }
}
